name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    inputs:
      aa:
        description: aa var
        required: true
        default: 'aa'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: df -h
      - run: echo $INPUT_AA
#      - run: npm install -g bats
#      - run: bats -v
#      - run: docker info
#      - run: docker-compose --version
