name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      AA: aa-${{ env.GITHUB_RUN_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: df -h
      - run: echo $AA
#      - run: npm install -g bats
#      - run: bats -v
#      - run: docker info
#      - run: docker-compose --version
