name: learn-github-actions
env:
  SS: 'ss'
on: 
  push:
    branches:
      - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo test > a.txt
      - run: cat a.txt
